print("God's plan, God's plan")
print("I hold back, sometimes I won't, yuh")
print("I feel good, sometimes I don't, ayy, don't")
print("I finessed down Weston Road, ayy, 'nessed")
print("Might go down a G.O.D., yeah, wait")
print("I go hard on Southside G, yeah, wait")
print("I make sure that north-side eat")