name = input("Enter your name: ")
first_course = input("Enter first course: ")
first_grade = input("Enter first course grade: ")
second_course = input("Enter second course: ")
second_grade = input("Enter second course grade: ")
third_course = input("Enter third course: ")
third_grade = input("Enter third course grade: ")
fourth_course = input("Enter fourth course: ")
fourth_grade = input("Enter fourth grade: ")
print("\n")
print(name)
print("--------------------------------------------------------")
print(f"{first_course}                           {first_grade}%")
print(f"{second_course}                            {second_grade}%")
print(f"{third_course}                           {third_grade}%")
print(f"{fourth_course}                           {fourth_grade}%")
print("Teacher comment: You are doing great keep up the great work")