name = input("Name: ")
DOB = input("Date of birth MM/DD/YY: ")
address = input("Address: ")
email = input("Email: ")
phone_number = input("Phone number: ")
print(f"Name: {name}")
print(f"Date of birth: {DOB}")
print(f"Address: {address}")
print(f"Email: {email}")
print(f"Phone number: {phone_number}")