number1 = int(input("Enter a number: "))
number2 = int(input("Enter another number: "))
print(f"Sum: {number1 + number2}")
print(f"Difference: {number1 - number2}")
print(f"Product: {number1 * number2}")
print(f"Quotient: {number1//number2}")