number1 = int(input("Type the first number: "))
number2 = int(input("Type the second number: "))
print(f"Sum: {number1 + number2}")
print(f"Difference: {number1 - number2}")
print(f"Product: {number1 * number2}")
print(f"Quotient: {number1//number2}")
print(f"Remainder: {number1 % number2}") 